

class DealerDailyData {


		Integer	enquiry3
		Integer	enquiry5
		Integer	enquiry6
		Integer	enquiry7
		Integer	enquiryX1
		Integer	enquiryX3
		Integer	enquiryX5
		Integer	enquiryX6
		Integer	enquiryZ4
		Integer enquiryGT
		Integer enquiryM
		Integer	enquiryTotal
		Integer	enquiryFollow3
		Integer	enquiryFollow5
		Integer	enquiryFollow6
		Integer	enquiryFollow7
		Integer	enquiryFollowX1
		Integer	enquiryFollowX3
		Integer	enquiryFollowX5
		Integer	enquiryFollowX6
		Integer	enquiryFollowZ4
		Integer	enquiryFollowGT
		Integer	enquiryFollowM
		Integer	enquiryFollowTotal
		Integer	bookings3
		Integer	bookings5
		Integer	bookings6
		Integer	bookings7
		Integer	bookingsX1
		Integer	bookingsX3
		Integer	bookingsX5
		Integer	bookingsX6
		Integer	bookingsZ4
		Integer	bookingsGT
		Integer	bookingsM
		Integer	bookingsTotal
		Integer	vehicles3
		Integer	vehicles5
		Integer	vehicles6
		Integer	vehicles7
		Integer	vehiclesX1
		Integer	vehiclesX3
		Integer	vehiclesX5
		Integer	vehiclesX6
		Integer	vehiclesZ4
		Integer	vehiclesGT
		Integer	vehiclesM
		Integer	vehiclesTotal
		Integer	enquiryNSC3
		Integer	enquiryNSC5
Integer	enquiryNSC6
		Integer	enquiryNSC7
	        Integer	enquiryNSCX1
	        Integer	enquiryNSCX3
	        Integer	enquiryNSCX5
	        Integer	enquiryNSCX6
	        Integer	enquiryNSCZ4
	        Integer	enquiryNSCGT
	        Integer	enquiryNSCM
	        Integer	enquiryNSCTotal
	        Integer	enquiryFollowNSC3
		Integer	enquiryFollowNSC5
		Integer	enquiryFollowNSC6
		Integer	enquiryFollowNSC7
		Integer	enquiryFollowNSCX1
		Integer	enquiryFollowNSCX3
		Integer	enquiryFollowNSCX5
		Integer	enquiryFollowNSCX6
		Integer	enquiryFollowNSCZ4
		Integer	enquiryFollowNSCGT
		Integer	enquiryFollowNSCM
	        Integer	enquiryFollowNSCTotal
	        Integer	bookingsNSC3
		Integer	bookingsNSC5
Integer	bookingsNSC6
		Integer	bookingsNSC7
		Integer	bookingsNSCX1
		Integer	bookingsNSCX3
		Integer	bookingsNSCX5
		Integer	bookingsNSCX6
		Integer	bookingsNSCZ4
		Integer	bookingsNSCGT
		Integer	bookingsNSCM
	        Integer	bookingsNSCTotal
		Integer	vehiclesNSC3
		Integer	vehiclesNSC5
		Integer	vehiclesNSC6
		Integer	vehiclesNSC7
		Integer	vehiclesNSCX1
		Integer	vehiclesNSCX3
		Integer	vehiclesNSCX5
		Integer	vehiclesNSCX6
		Integer	vehiclesNSCZ4
		Integer	vehiclesNSCGT
		Integer	vehiclesNSCM
	        Integer	vehiclesNSCTotal
	        Integer	closingStock3
		Integer	closingStock5
		Integer	closingStock6
		Integer	closingStock7
		Integer	closingStockX1
		Integer	closingStockX3
		Integer	closingStockX5
		Integer	closingStockX6
		Integer	closingStockZ4
		Integer	closingStockGT
		Integer	closingStockM
		Integer	closingStockTotal
		Integer	testDrives3
		Integer	testDrives5
		Integer	testDrives6
		Integer	testDrives7
		Integer	testDrivesX1
		Integer	testDrivesX3
		Integer	testDrivesX5
		Integer	testDrivesX6
		Integer	testDrivesZ4
		Integer	testDrivesGT
		Integer	testDrivesM
		Integer	testDrivesTotal
		String user
		
		Integer day
		Integer year
		Integer month
		
		static belongsTo = [Person]
    static constraints = {
     	enquiry3 (blank:false)
     	enquiry5 (blank:false)
		enquiry6 (blank:false)
     	enquiry7 (blank:false) 
     	enquiryX1 (blank:false)
     	enquiryX3 (blank:false)
     	enquiryX5 (blank:false)
	enquiryX6 (blank:false)
     	enquiryGT (blank:false)
     	enquiryZ4 (blank:false)
     	enquiryM (blank:false)
     	enquiryTotal (blank:true)
     	enquiryFollow3 (blank:false)
     	enquiryFollow5 (blank:false)
	enquiryFollow6 (blank:false)
     	enquiryFollow7 (blank:false)
     	enquiryFollowX1 (blank:false)
     	enquiryFollowX3 (blank:false)
     	enquiryFollowX5 (blank:false)
     	enquiryFollowX6 (blank:false)
     	enquiryFollowGT (blank:false)
     	enquiryFollowZ4 (blank:false)
     	enquiryFollowM (blank:false)
     	enquiryFollowTotal (blank:true)
     	bookings3 (blank:false)
     	bookings5 (blank:false)
     	bookings6 (blank:false)
	bookings7 (blank:false)
     	bookingsX1 (blank:false)
     	bookingsX3 (blank:false)
     	bookingsX5 (blank:false)
     	bookingsX6 (blank:false)
     	bookingsZ4 (blank:false)
     	bookingsGT (blank:false)
     	bookingsM (blank:false)
     	bookingsTotal (blank:true)
     	vehicles3 (blank:false)
     	vehicles5 (blank:false)
     	vehicles6 (blank:false)
     	vehicles7 (blank:false)
     	vehiclesX1 (blank:false)
     	vehiclesX3 (blank:false)
     	vehiclesX5 (blank:false)
     	vehiclesX6 (blank:false)
     	vehiclesZ4 (blank:false)
     	vehiclesGT (blank:false)
     	vehiclesM (blank:false)
     	vehiclesTotal (blank:true)
     	enquiryNSC3 (blank:false)
     	enquiryNSC5 (blank:false)
     	enquiryNSC6 (blank:false)
     	enquiryNSC7 (blank:false)
	enquiryNSCX1 (blank:false)
	     enquiryNSCX3 (blank:false)
	     enquiryNSCX5 (blank:false)
	enquiryNSCX6 (blank:false)
	     enquiryNSCZ4 (blank:false)
	     enquiryNSCGT (blank:false)
	     enquiryNSCM (blank:false)
        enquiryNSCTotal (blank:true)
        enquiryFollowNSC3 (blank:false)
     	enquiryFollowNSC5 (blank:false)
     	enquiryFollowNSC6 (blank:false)
     	enquiryFollowNSC7 (blank:false)
     	enquiryFollowNSCX1 (blank:false)
     	enquiryFollowNSCX3 (blank:false)
     	enquiryFollowNSCX5 (blank:false)
     	enquiryFollowNSCX6 (blank:false)
     	enquiryFollowNSCZ4 (blank:false)
     	enquiryFollowNSCGT (blank:false)
     	enquiryFollowNSCM (blank:false)
         enquiryFollowNSCTotal   (blank:true)
        bookingsNSC3 (blank:false)
     	bookingsNSC5 (blank:false)
     	bookingsNSC6 (blank:false)
     	bookingsNSC7 (blank:false)
     	bookingsNSCX1 (blank:false)
     	bookingsNSCX3 (blank:false)
     	bookingsNSCX5 (blank:false)
     	bookingsNSCX6 (blank:false)
     	bookingsNSCZ4 (blank:false)
     	bookingsNSCGT (blank:false)
     	bookingsNSCM (blank:false)
         bookingsNSCTotal (blank:true)
     	vehiclesNSC3 (blank:false)
     	vehiclesNSC5 (blank:false)
     	vehiclesNSC6 (blank:false)
     	vehiclesNSC7 (blank:false)
     	vehiclesNSCX1 (blank:false)
     	vehiclesNSCX3 (blank:false)
     	vehiclesNSCX5 (blank:false)
     	vehiclesNSCX6 (blank:false)
     	vehiclesNSCZ4 (blank:false)
     	vehiclesNSCGT (blank:false)
     	vehiclesNSCM (blank:false)
     	vehiclesNSCTotal (blank:true)
        closingStock3 (blank:false)
     	closingStock5 (blank:false)
     	closingStock6 (blank:false)
     	closingStock7 (blank:false)
     	closingStockX1 (blank:false)
     	closingStockX3 (blank:false)
     	closingStockX5 (blank:false)
     	closingStockX6 (blank:false)
     	closingStockZ4 (blank:false)
     	closingStockGT (blank:false)
     	closingStockM (blank:false)
     	closingStockTotal (blank:true)
     	testDrives3 (blank:false)
     	testDrives5 (blank:false)
     	testDrives6 (blank:false)
     	testDrives7 (blank:false)
     	testDrivesX1 (blank:false)
     	testDrivesX3 (blank:false)
     	testDrivesX5 (blank:false)
     	testDrivesX6 (blank:false)
     	testDrivesZ4 (blank:false)
     	testDrivesGT (blank:false)
     	testDrivesM (blank:false)
 	testDrivesTotal (blank:true)
    }
}
